-- MySQL Script generated by MySQL Workbench
-- Mon Mar 31 22:56:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escoladb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escoladb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escoladb` DEFAULT CHARACTER SET utf8 ;
USE `escoladb` ;

-- -----------------------------------------------------
-- Table `escoladb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `bi_numero` VARCHAR(14) NOT NULL,
  `tipo` ENUM(' diretor_geral', ' diretor_pedagogico', 'coordenador', 'professor', 'aluno', 'secretaria') NOT NULL,
  `status` ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
  `foto_perfil` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_curso`),
  UNIQUE INDEX `id_curso_UNIQUE` (`id_curso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`turma` (
  `id_turma` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `curso_id_curso` INT NOT NULL,
  `curso_id_curso1` INT NOT NULL,
  PRIMARY KEY (`id_turma`, `curso_id_curso1`),
  UNIQUE INDEX `id_turma_UNIQUE` (`id_turma` ASC) VISIBLE,
  INDEX `fk_curso4_idx` (`curso_id_curso1` ASC) VISIBLE,
  CONSTRAINT `fk_curso4`
    FOREIGN KEY (`curso_id_curso1`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `numero_matricula` VARCHAR(20) NOT NULL,
  `ano_letivo` YEAR NULL,
  `usuario_id_usuario` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `turma_id_turma1` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_aluno`, `usuario_id_usuario`, `turma_id_turma1`, `curso_id_curso`),
  UNIQUE INDEX `id_aluno_UNIQUE` (`id_aluno` ASC) VISIBLE,
  INDEX `fk_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_turma1_idx` (`turma_id_turma1` ASC) VISIBLE,
  INDEX `fk_curso1_idx` (`curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma1`
    FOREIGN KEY (`turma_id_turma1`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso1`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_professor`, `usuario_id_usuario`),
  UNIQUE INDEX `id_professor_UNIQUE` (`id_professor` ASC) VISIBLE,
  INDEX `fk_usuario3_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_curso3_idx` (`curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_usuario3`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso3`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`coordenador` (
  `id_coordenador` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_coordenador`, `usuario_id_usuario`, `curso_id_curso`),
  UNIQUE INDEX `id_coordenador_UNIQUE` (`id_coordenador` ASC) VISIBLE,
  INDEX `fk_usuario2_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_curso2_idx` (`curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_usuario2`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso2`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`secretaria` (
  `id_secretaria` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(50) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_secretaria`, `usuario_id_usuario`),
  UNIQUE INDEX `id_secretaria_UNIQUE` (`id_secretaria` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`disciplina` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `curso_id_curso` INT NOT NULL,
  `professor_id_professor` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`, `curso_id_curso`, `professor_id_professor`),
  UNIQUE INDEX `id_disciplina_UNIQUE` (`id_disciplina` ASC) VISIBLE,
  INDEX `fk_curso5_idx` (`curso_id_curso` ASC) VISIBLE,
  INDEX `fk_professor5_idx` (`professor_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_curso5`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor5`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`nota` (
  `id_nota` INT NOT NULL,
  `nota` DECIMAL(2,5) NOT NULL,
  `data` DATE NOT NULL,
  `aluno_id_aluno` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_nota`, `disciplina_id_disciplina`),
  UNIQUE INDEX `id_nota_UNIQUE` (`id_nota` ASC) VISIBLE,
  INDEX `fk_aluno1_idx` (`aluno_id_aluno` ASC) VISIBLE,
  INDEX `fk_disciplina1_idx` (`disciplina_id_disciplina` ASC) VISIBLE,
  CONSTRAINT `fk_aluno1`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina1`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`comunicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`comunicado` (
  `id_comunicado` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comunicado`),
  UNIQUE INDEX `id_comunicado_UNIQUE` (`id_comunicado` ASC) VISIBLE,
  INDEX `fk_usuario5_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario5`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`password_reset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`password_reset` (
  `id_password_reset` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `expira_em` TIMESTAMP NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_password_reset`),
  UNIQUE INDEX `id_password_reset_UNIQUE` (`id_password_reset` ASC) VISIBLE,
  INDEX `fk_usuario4_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario4`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`frequencia_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`frequencia_aluno` (
  `id_frequencia_aluno` INT NOT NULL AUTO_INCREMENT,
  `data_aula` DATE NOT NULL,
  `presenca` ENUM('presente', 'ausente', 'justificado') NOT NULL DEFAULT 'ausente',
  `aluno_id_aluno` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_frequencia_aluno`, `disciplina_id_disciplina`, `turma_id_turma`),
  INDEX `fk_aluno2_idx` (`aluno_id_aluno` ASC) VISIBLE,
  UNIQUE INDEX `id_frequencia_aluno_UNIQUE` (`id_frequencia_aluno` ASC) VISIBLE,
  INDEX `fk_disciplina4_idx` (`disciplina_id_disciplina` ASC) VISIBLE,
  INDEX `fk_turma4_idx` (`turma_id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_aluno2`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina4`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma4`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`materiais_apoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`materiais_apoio` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `caminho_arquivo` VARCHAR(255) NOT NULL,
  `data_envio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_material`),
  UNIQUE INDEX `id_material_UNIQUE` (`id_material` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`cronograma_aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`cronograma_aula` (
  `id_cronograma_aula` INT NOT NULL,
  `dia_semana` ENUM('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado') NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_fim` TIME NOT NULL,
  `sala` VARCHAR(10) NOT NULL,
  `id_professor` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_cronograma_aula`, `turma_id_turma`),
  INDEX `fk_professor3_idx` (`id_professor` ASC) VISIBLE,
  INDEX `fk_turma7_idx` (`turma_id_turma` ASC) VISIBLE,
  INDEX `fk_disciplina5_idx` (`id_disciplina` ASC) VISIBLE,
  CONSTRAINT `fk_professor3`
    FOREIGN KEY (`id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma7`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina5`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`historico_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`historico_professor` (
  `id_historico_professor` INT NOT NULL AUTO_INCREMENT,
  `carga_horaria` INT NOT NULL,
  `status` ENUM('ativo', 'inativo', 'afastado') NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL,
  `professor_id_professor` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_historico_professor`),
  INDEX `fk_professor1_idx` (`professor_id_professor` ASC) VISIBLE,
  INDEX `fk_disciplina3_idx` (`disciplina_id_disciplina` ASC) VISIBLE,
  INDEX `fk_turma5_idx` (`turma_id_turma` ASC) VISIBLE,
  UNIQUE INDEX `id_historico_professor_UNIQUE` (`id_historico_professor` ASC) VISIBLE,
  CONSTRAINT `fk_professor1`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina3`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma5`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`matricula` (
  `id_matricula` INT NOT NULL,
  `ano_letivo` YEAR NOT NULL,
  `data_matricula` DATE NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `aluno_id_aluno` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_matricula`, `turma_id_turma`, `aluno_id_aluno`, `curso_id_curso`),
  UNIQUE INDEX `id_matricula_UNIQUE` (`id_matricula` ASC) VISIBLE,
  INDEX `fk_turma6_idx` (`turma_id_turma` ASC) VISIBLE,
  INDEX `fk_aluno3_idx` (`aluno_id_aluno` ASC) VISIBLE,
  INDEX `fk_curso6_idx` (`curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_turma6`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno3`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso6`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`professor_tem_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor_tem_turma` (
  `professor_id_professor` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`professor_id_professor`, `turma_id_turma`),
  INDEX `fk_turma2_idx` (`turma_id_turma` ASC) VISIBLE,
  INDEX `fk_professor2_idx` (`professor_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_professor2`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma2`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`materiais_apoio_tem_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`materiais_apoio_tem_usuario` (
  `materiais_apoio_id_material` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`materiais_apoio_id_material`, `usuario_id_usuario`),
  INDEX `fk_materiais_apoio1_idx` (`materiais_apoio_id_material` ASC) VISIBLE,
  INDEX `fk_usuario6_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_materiais_apoio1`
    FOREIGN KEY (`materiais_apoio_id_material`)
    REFERENCES `escoladb`.`materiais_apoio` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario6`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`professor_tem_turma1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor_tem_turma1` (
  `professor_id_professor` INT NOT NULL,
  `professor_usuario_id_usuario` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`professor_id_professor`, `professor_usuario_id_usuario`, `turma_id_turma`),
  INDEX `fk_turma3_idx` (`turma_id_turma` ASC) VISIBLE,
  INDEX `fk_professor4_idx` (`professor_id_professor` ASC, `professor_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_professor4`
    FOREIGN KEY (`professor_id_professor` , `professor_usuario_id_usuario`)
    REFERENCES `escoladb`.`professor` (`id_professor` , `usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma3`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
