-- MySQL Script generated by MySQL Workbench
-- Mon Mar 31 23:25:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escoladb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escoladb` DEFAULT CHARACTER SET utf8;
USE `escoladb`;

-- -----------------------------------------------------
-- Table `escoladb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `senha` VARCHAR(255) NOT NULL,
  `bi_numero` VARCHAR(14) NOT NULL UNIQUE,
  `tipo` ENUM('diretor_geral', 'diretor_pedagogico', 'coordenador', 'professor', 'aluno', 'secretaria') NOT NULL,
  `status` ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
  `foto_perfil` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_curso`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `curso_id_curso` INT NOT NULL,
  `classe` ENUM('10ª', '11ª', '12ª', '13ª') NOT NULL,
  `turno` ENUM('Manha', 'Tarde', 'Noite') NOT NULL DEFAULT 'Manha',
  PRIMARY KEY (`id_turma`),
  INDEX `fk_curso4_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_curso4`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `data_nascimento` DATE NOT NULL,
  `genero` VARCHAR(10) NOT NULL,
  `naturalidade` VARCHAR(100) NOT NULL,
  `nacionalidade` VARCHAR(100) NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `ano_letivo` YEAR NOT NULL,
  `nome_encarregado` VARCHAR(100) NOT NULL,
  `contacto_encarregado` VARCHAR(20) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_turma1_idx` (`turma_id_turma` ASC),
  CONSTRAINT `fk_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma1`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_professor`),
  INDEX `fk_usuario3_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_curso3_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_usuario3`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso3`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`coordenador` (
  `id_coordenador` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_coordenador`),
  INDEX `fk_usuario2_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_curso2_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_usuario2`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso2`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`secretaria` (
  `id_secretaria` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(50) NOT NULL,
  `pode_registrar` TINYINT(1) NOT NULL DEFAULT 0,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_secretaria`),
  INDEX `fk_usuario_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`disciplina` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`, `curso_id_curso`),
  UNIQUE INDEX `id_disciplina_UNIQUE` (`id_disciplina`),
  INDEX `fk_curso5_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_curso5`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`professor_tem_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor_tem_disciplina` (
  `professor_id_professor` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  PRIMARY KEY (`professor_id_professor`, `disciplina_id_disciplina`),
  INDEX `fk_disciplina_idx` (`disciplina_id_disciplina` ASC),
  CONSTRAINT `fk_professor_disciplina_professor`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_professor_disciplina_disciplina`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`nota` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `nota` DECIMAL(5,2) NOT NULL,
  `data` DATE NOT NULL,
  `tipo_avaliacao` ENUM('prova', 'avaliacao_continua', 'trabalho', 'recuperacao', 'projeto') NOT NULL DEFAULT 'prova',
  `trimestre` TINYINT(1) NULL,
  `descricao` VARCHAR(100) NULL,
  `peso` DECIMAL(3,2) NOT NULL DEFAULT 1.00,
  `aluno_id_aluno` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_aluno1_idx` (`aluno_id_aluno` ASC),
  INDEX `fk_disciplina1_idx` (`disciplina_id_disciplina` ASC),
  CONSTRAINT `fk_aluno1`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disciplina1`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`comunicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`comunicado` (
  `id_comunicado` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comunicado`),
  INDEX `fk_usuario5_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_usuario5`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;
  
  -- Remova a coluna destinatario_id se existir
ALTER TABLE `escoladb`.`comunicado` DROP FOREIGN KEY `fk_comunicado_destinatario`;
ALTER TABLE `escoladb`.`comunicado` DROP COLUMN `destinatario_id`;
-- Corrigir a tabela de destinatários para manter consistência com a tabela usuario
ALTER TABLE `escoladb`.`comunicado_destinatario` 
MODIFY COLUMN `tipo_destinatario` ENUM('diretor_geral', 'diretor_pedagogico', 'coordenador', 'professor', 'aluno', 'secretaria', 'todos') NOT NULL;

-- Crie uma tabela para os tipos de destinatários
CREATE TABLE IF NOT EXISTS `escoladb`.`comunicado_destinatario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comunicado_id` INT NOT NULL,
  `tipo_destinatario` ENUM('aluno', 'professor', 'coordenador', 'secretaria', 'diretor_geral', 'diretor_pedagogico', 'todos') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comunicado_idx` (`comunicado_id` ASC),
  CONSTRAINT `fk_comunicado_destinatario`
    FOREIGN KEY (`comunicado_id`)
    REFERENCES `escoladb`.`comunicado` (`id_comunicado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;
  
  
-- -----------------------------------------------------
-- Table `escoladb`.`frequencia_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`frequencia_aluno` (
  `id_frequencia_aluno` INT NOT NULL AUTO_INCREMENT,
  `data_aula` DATE NOT NULL,
  `presenca` ENUM('presente', 'ausente', 'justificado') NOT NULL DEFAULT 'ausente',
  `tipo_aula` ENUM('normal', 'reposicao', 'atividade_externa') NOT NULL DEFAULT 'normal',
  `observacao` TEXT NULL,
  `aluno_id_aluno` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_frequencia_aluno`),
  INDEX `fk_aluno2_idx` (`aluno_id_aluno` ASC),
  INDEX `fk_disciplina4_idx` (`disciplina_id_disciplina` ASC),
  INDEX `fk_turma4_idx` (`turma_id_turma` ASC),
  CONSTRAINT `fk_aluno2`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disciplina4`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma4`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`materiais_apoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`materiais_apoio` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `caminho_arquivo` VARCHAR(255) NOT NULL,
  `disciplina_id` INT NULL,
  `curso_id` INT NOT NULL,
  `classe` ENUM('10ª', '11ª', '12ª', '13ª', 'todas') NULL,
  `usuario_id_upload` INT NOT NULL,
  `data_upload` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_material`),
  INDEX `fk_materiais_disciplina_idx` (`disciplina_id` ASC),
  INDEX `fk_materiais_curso_idx` (`curso_id` ASC),
  INDEX `fk_materiais_usuario_idx` (`usuario_id_upload` ASC),
  CONSTRAINT `fk_materiais_disciplina`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_materiais_curso`
    FOREIGN KEY (`curso_id`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_materiais_usuario`
    FOREIGN KEY (`usuario_id_upload`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;
  
DROP TABLE IF EXISTS `escoladb`.`materiais_apoio`;
-- Remover a tabela antiga de relacionamento (se existir)
DROP TABLE IF EXISTS `escoladb`.`materiais_apoio_tem_usuario`;

-- Criar tabela de destinatários para materiais de apoio
CREATE TABLE IF NOT EXISTS `escoladb`.`material_destinatario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `material_id` INT NOT NULL,
  `tipo_destino` ENUM('turma', 'curso', 'classe') NOT NULL,
  `turma_id` INT NULL,
  `curso_id` INT NULL,
  `classe` ENUM('10ª', '11ª', '12ª', '13ª') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_material_idx` (`material_id`),
  INDEX `fk_turma_destino_idx` (`turma_id`),
  INDEX `fk_curso_destino_idx` (`curso_id`),
  CONSTRAINT `fk_material_destino`
    FOREIGN KEY (`material_id`)
    REFERENCES `escoladb`.`materiais_apoio` (`id_material`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_material_turma_destino`
    FOREIGN KEY (`turma_id`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_material_curso_destino`
    FOREIGN KEY (`curso_id`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `escoladb`.`cronograma_aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`cronograma_aula` (
  `id_cronograma_aula` INT NOT NULL AUTO_INCREMENT,
  `dia_semana` ENUM('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado') NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_fim` TIME NOT NULL,
  `sala` VARCHAR(10) NOT NULL,
  `id_professor` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_cronograma_aula`),
  INDEX `fk_professor3_idx` (`id_professor` ASC),
  INDEX `fk_turma7_idx` (`turma_id_turma` ASC),
  INDEX `fk_disciplina5_idx` (`id_disciplina` ASC),
  CONSTRAINT `fk_professor3`
    FOREIGN KEY (`id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma7`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disciplina5`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`historico_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`historico_professor` (
  `id_historico` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `descricao` TEXT NULL,
  `professor_id_professor` INT NOT NULL,
  `disciplina_id_disciplina` INT NULL,
  `turma_id_turma` INT NULL,
  `cargo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_historico`),
  INDEX `fk_professor2_idx` (`professor_id_professor` ASC),
  INDEX `fk_disciplina_historico_idx` (`disciplina_id_disciplina` ASC),
  INDEX `fk_turma_historico_idx` (`turma_id_turma` ASC),
  CONSTRAINT `fk_professor2`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disciplina_historico`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma_historico`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `ano_letivo` YEAR NOT NULL,
  `numero_matricula` VARCHAR(20) NOT NULL UNIQUE,
  `data_matricula` DATE NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `aluno_id_aluno` INT NOT NULL,
  `status_matricula` ENUM('ativa', 'trancada', 'cancelada') NOT NULL DEFAULT 'ativa',
  `comprovativo_pagamento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_turma6_idx` (`turma_id_turma` ASC),
  INDEX `fk_aluno3_idx` (`aluno_id_aluno` ASC),
  CONSTRAINT `fk_turma6`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aluno3`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`professor_tem_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor_tem_turma` (
  `professor_id_professor` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`professor_id_professor`, `turma_id_turma`),
  INDEX `idx_turma2` (`turma_id_turma` ASC),
  INDEX `idx_professor2` (`professor_id_professor` ASC),
  CONSTRAINT `fk_professor_tem_turma_professor`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_tem_turma_turma`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`documentos_administrativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`documentos_administrativos` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL,
  `caminho_arquivo` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `data_upload` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_usuario7_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_usuario7`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Melhorias na tabela documentos_administrativos
ALTER TABLE `escoladb`.`documentos_administrativos` 
ADD COLUMN `data_publicacao` DATETIME NULL AFTER `data_upload`,
ADD COLUMN `visibilidade` ENUM('publico', 'restrito') NOT NULL DEFAULT 'restrito';

-- Tabela de destinatários melhorada
CREATE TABLE IF NOT EXISTS `escoladb`.`documento_destinatarios` (
  `id_destinatarios` INT NOT NULL AUTO_INCREMENT,
  `documento_id` INT NOT NULL,
  `tipo_destino` ENUM('usuario', 'turma', 'curso', 'tipo_usuario') NOT NULL,
  `usuario_id` INT NULL,
  `turma_id` INT NULL,
  `curso_id` INT NULL,
  `tipo_usuario` ENUM('diretor_geral', 'diretor_pedagogico', 'coordenador', 'professor', 'aluno', 'secretaria') NULL,
  PRIMARY KEY (`id_destinatarios`),
  INDEX `fk_documento_idx` (`documento_id`),
  INDEX `fk_usuario_destino_idx` (`usuario_id`),
  INDEX `fk_turma_destino_idx` (`turma_id`),
  INDEX `fk_curso_destino_idx` (`curso_id`),
  CONSTRAINT `fk_documento_destino`
    FOREIGN KEY (`documento_id`)
    REFERENCES `escoladb`.`documentos_administrativos` (`id_documento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_destino`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma_destino`
    FOREIGN KEY (`turma_id`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_curso_destino`
    FOREIGN KEY (`curso_id`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`plano_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`plano_ensino` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `ano_letivo` YEAR NOT NULL,
  `trimestre` ENUM('1', '2', '3', 'anual') NOT NULL,
  `conteudo_programatico` TEXT NOT NULL,
  `metodologia` TEXT NOT NULL,
  `criterios_avaliacao` TEXT NOT NULL,
  `bibliografia` TEXT NOT NULL,
  `status` ENUM('rascunho', 'submetido', 'aprovado', 'rejeitado') NOT NULL DEFAULT 'rascunho',
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_submissao` DATETIME NULL,
  `data_aprovacao` DATETIME NULL,
  `motivo_rejeicao` TEXT NULL,
  `id_disciplina` INT NOT NULL,
  `id_professor` INT NULL,
  `id_diretor_aprovador` INT NULL,
  `caminho_arquivo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_plano`),
  INDEX `fk_disciplina_plano_idx` (`id_disciplina` ASC),
  INDEX `fk_professor_plano_idx` (`id_professor` ASC),
  INDEX `fk_diretor_plano_idx` (`id_diretor_aprovador` ASC),
  CONSTRAINT `fk_disciplina_plano`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_professor_plano`
    FOREIGN KEY (`id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_diretor_plano`
    FOREIGN KEY (`id_diretor_aprovador`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`relatorio`
-- -----------------------------------------------------
-- Primeiro, vamos remover a tabela existente (se necessário)
-- DROP TABLE IF EXISTS `escoladb`.`relatorio`;

CREATE TABLE IF NOT EXISTS `escoladb`.`relatorio` (
  `id_relatorio` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `tipo` ENUM('matriculas', 'notas', 'frequencia', 'desempenho', 'planos_ensino', 'transferencias', 'outros') NOT NULL,
  `data_geracao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `periodicidade` ENUM('unico', 'diario', 'semanal', 'mensal', 'trimestral', 'anual') NULL DEFAULT 'unico',
  `ano_letivo` YEAR NOT NULL,
  `trimestre` TINYINT(1) NULL,
  `curso_id` INT NULL,
  `turma_id` INT NULL,
  `classe` ENUM('10ª', '11ª', '12ª', '13ª') NULL,
  `caminho_arquivo` VARCHAR(255) NULL COMMENT 'Caminho onde o PDF foi salvo (opcional)',
  `usuario_id_gerador` INT NOT NULL,
  `observacoes` TEXT NULL,
  PRIMARY KEY (`id_relatorio`),
  INDEX `fk_usuario_relatorio_idx` (`usuario_id_gerador` ASC),
  INDEX `fk_curso_relatorio_idx` (`curso_id` ASC),
  INDEX `fk_turma_relatorio_idx` (`turma_id` ASC),
  CONSTRAINT `fk_usuario_relatorio`
    FOREIGN KEY (`usuario_id_gerador`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`),
  CONSTRAINT `fk_curso_relatorio`
    FOREIGN KEY (`curso_id`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma_relatorio`
    FOREIGN KEY (`turma_id`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `escoladb`.`relatorio_destinatario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `relatorio_id` INT NOT NULL,
  `tipo_destino` ENUM('usuario', 'turma', 'curso', 'tipo_usuario') NOT NULL,
  `usuario_id` INT NULL,
  `turma_id` INT NULL,
  `curso_id` INT NULL,
  `tipo_usuario` ENUM('diretor_geral', 'diretor_pedagogico', 'coordenador', 'professor', 'aluno', 'secretaria') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relatorio_idx` (`relatorio_id`),
  CONSTRAINT `fk_relatorio_destino`
    FOREIGN KEY (`relatorio_id`)
    REFERENCES `escoladb`.`relatorio` (`id_relatorio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- ---------------------------------------------------
-- Insert default accounts
INSERT INTO `escoladb`.`usuario` (nome, email, senha, bi_numero, tipo, status)
VALUES 
  ('Diretor Geral', 'diretor@gmail.com', '$2y$10$qWet6EoL5adPKpYD5/iV3O.JhwWAIiBvfpBL5aJdMdnFdB4f6U14C', '456456789LA123', 'diretor_geral', 'ativo'),
  ('Diretor Pedagógico', 'pedagogico@gmail.com', '$2y$10$qWet6EoL5adPKpYD5/iV3O.JhwWAIiBvfpBL5aJdMdnFdB4f6U14C', '789456789LA123', 'diretor_pedagogico', 'ativo'),
  ('Secretaria Padrão', 'secretaria@gmail.com', '$2y$10$NAqP/Mb7shCRenhNzDZRAuXdht0z2SjF8pLgWpKA9JXgbZMkiT.4O', '989456789LA128', 'secretaria', 'ativo');

INSERT INTO `escoladb`.`secretaria` (setor, pode_registrar, usuario_id_usuario) 
VALUES ('Administrativo', 1, LAST_INSERT_ID());

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;