-- MySQL Script generated by MySQL Workbench
-- Mon Mar 31 23:25:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escoladb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escoladb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escoladb` DEFAULT CHARACTER SET utf8 ;
USE `escoladb` ;

-- -----------------------------------------------------
-- Table `escoladb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `senha` VARCHAR(255) NOT NULL,
  `bi_numero` VARCHAR(14) NOT NULL UNIQUE,
  `tipo` ENUM('diretor_geral', 'diretor_pedagogico', 'coordenador', 'professor', 'aluno', 'secretaria') NOT NULL,
  `status` ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
  `foto_perfil` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`)
) ENGINE = InnoDB;

-- Conta padrão da Secretaria
INSERT INTO `escoladb`.`usuario` (nome, email, senha, bi_numero, tipo, status)
VALUES ('Secretaria Geral', 'secretaria@aldalara.com', 'senha_hash', '0000000000000', 'secretaria', 'ativo');

-- Conta padrão do Diretor Geral
INSERT INTO `escoladb`.`usuario` (nome, email, senha, bi_numero, tipo, status)
VALUES ('Diretor Geral', 'diretor@gmail.com', '$2y$10$cJqlwZa/fiGP7b3zfZ0CA.mGxcYJz4QJCMIAyd8h0wZL9TBKQt0hW', '456456789LA123' , 'diretor_geral', 'ativo');

-- Conta padrão do Diretor Pedagógico
INSERT INTO `escoladb`.`usuario` (nome, email, senha, bi_numero, tipo, status)
VALUES ('Diretor Pedagógico', 'pedagogico@gmail.com', '$2y$10$cJqlwZa/fiGP7b3zfZ0CA.mGxcYJz4QJCMIAyd8h0wZL9TBKQt0hW', '789456789LA123' ,'diretor_pedagogico', 'ativo');


-- -----------------------------------------------------
-- Table `escoladb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_curso4_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_curso4`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

ALTER TABLE `escoladb`.`turma` 
ADD COLUMN `classe` VARCHAR(10) NOT NULL AFTER `curso_id_curso`;

-- 1. Primeiro, adicionar a coluna turno na tabela turma
ALTER TABLE `escoladb`.`turma`
ADD COLUMN `turno` VARCHAR(20) NOT NULL DEFAULT 'Manhã' COMMENT 'Turno da turma (Manhã, Tarde, Noite, Integral)';

-- 4. Remover a coluna turno da tabela matricula (opcional, se quiser manter histórico)
-- ALTER TABLE matricula DROP COLUMN turno;

-- 5. Se decidir remover definitivamente da matricula:
ALTER TABLE `escoladb`.`matricula` 
DROP COLUMN turno;

-- -----------------------------------------------------
-- Table `escoladb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `data_nascimento` DATE NOT NULL,
  `genero` VARCHAR(10) NOT NULL,
  `naturalidade` VARCHAR(100) NOT NULL,
  `nacionalidade` VARCHAR(100) NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `ano_letivo` YEAR NOT NULL,
  `nome_encarregado` VARCHAR(100) NOT NULL,
  `contacto_encarregado` VARCHAR(20) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_turma1_idx` (`turma_id_turma` ASC),
  INDEX `fk_curso1_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma1`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso1`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_professor`),
  INDEX `fk_usuario3_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_curso3_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_usuario3`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso3`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`coordenador` (
  `id_coordenador` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_coordenador`),
  INDEX `fk_usuario2_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_curso2_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_usuario2`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso2`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`secretaria` (
  `id_secretaria` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(50) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_secretaria`),
  INDEX `fk_usuario_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


ALTER TABLE `escoladb`.`secretaria` 
ADD COLUMN `pode_registrar` TINYINT(1) NOT NULL DEFAULT 0 AFTER `setor`;

-- Inserir usuário padrão da secretaria
INSERT INTO `escoladb`.`usuario` (nome, email, senha, bi_numero, tipo, status) 
VALUES ('Secretaria Padrão', 'secretaria@gmail.com', 'admin', '123456789LA123', 'secretaria', 'ativo');

-- Inserir registro da secretaria com permissão para registrar outras
INSERT INTO `escoladb`.`secretaria` (setor, pode_registrar, usuario_id_usuario) 
VALUES ('Administrativo', 1, LAST_INSERT_ID());


-- -----------------------------------------------------
-- Table `escoladb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE `escoladb`.`disciplina` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `curso_id_curso` INT NOT NULL,
  `classe` VARCHAR(10) NOT NULL,  -- Adicionado para vincular disciplina a uma classe específica
  PRIMARY KEY (`id_disciplina`, `curso_id_curso`),
  UNIQUE INDEX `id_disciplina_UNIQUE` (`id_disciplina`),
  INDEX `fk_curso5_idx` (`curso_id_curso`),
  CONSTRAINT `fk_curso5`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

ALTER TABLE `escoladb`.`disciplina` 
ADD COLUMN `classe` VARCHAR(10) NOT NULL AFTER `curso_id_curso`;

ALTER TABLE `escoladb`.`disciplina` 
DROP FOREIGN KEY `fk_professor5`;

ALTER TABLE `escoladb`.`disciplina` 
DROP COLUMN `professor_id_professor`;

-- -----------------------------------------------------
-- Table `escoladb`.`professor_tem_turma`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `escoladb`.`professor_tem_disciplina` (
  `professor_id_professor` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  `classe` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`professor_id_professor`, `disciplina_id_disciplina`, `classe`),
  INDEX `fk_disciplina_idx` (`disciplina_id_disciplina` ASC),
  CONSTRAINT `fk_professor_disciplina_professor`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_professor_disciplina_disciplina`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`nota` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `nota` DECIMAL(5,2) NOT NULL,
  `data` DATE NOT NULL,
  `tipo_avaliacao` ENUM('prova', 'avaliacao_continua', 'trabalho', 'recuperacao', 'projeto') NOT NULL DEFAULT 'prova',
  `trimestre` TINYINT(1) NULL,
  `descricao` VARCHAR(100) NULL,
  `peso` DECIMAL(3,2) NOT NULL DEFAULT 1.00,
  `aluno_id_aluno` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_aluno1_idx` (`aluno_id_aluno` ASC),
  INDEX `fk_disciplina1_idx` (`disciplina_id_disciplina` ASC),
  CONSTRAINT `fk_aluno1`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disciplina1`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`comunicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`comunicado` (
  `id_comunicado` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comunicado`),
  INDEX `fk_usuario5_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_usuario5`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `escoladb`.`password_reset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`password_reset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `expira_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `escoladb`.`frequencia_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`frequencia_aluno` (
  `id_frequencia_aluno` INT NOT NULL AUTO_INCREMENT,
  `data_aula` DATE NOT NULL,
  `presenca` ENUM('presente', 'ausente', 'justificado') NOT NULL DEFAULT 'ausente',
  `tipo_aula` ENUM('normal', 'reposicao', 'atividade_externa') NOT NULL DEFAULT 'normal',
  `observacao` TEXT NULL,
  `aluno_id_aluno` INT NOT NULL,
  `disciplina_id_disciplina` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_frequencia_aluno`),
  INDEX `fk_aluno2_idx` (`aluno_id_aluno` ASC),
  INDEX `fk_disciplina4_idx` (`disciplina_id_disciplina` ASC),
  INDEX `fk_turma4_idx` (`turma_id_turma` ASC),
  CONSTRAINT `fk_aluno2`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disciplina4`
    FOREIGN KEY (`disciplina_id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma4`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`materiais_apoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`materiais_apoio` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `caminho_arquivo` VARCHAR(255) NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_material`),
  INDEX `fk_disciplina2_idx` (`id_disciplina` ASC),
  CONSTRAINT `fk_disciplina2`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


ALTER TABLE `escoladb`.`materiais_apoio` 
ADD COLUMN `data_upload` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `id_disciplina`;

-- -----------------------------------------------------
-- Table `escoladb`.`cronograma_aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`cronograma_aula` (
  `id_cronograma_aula` INT NOT NULL AUTO_INCREMENT,
  `dia_semana` ENUM('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado') NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_fim` TIME NOT NULL,
  `sala` VARCHAR(10) NOT NULL,
  `id_professor` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_cronograma_aula`),
  INDEX `fk_professor3_idx` (`id_professor` ASC),
  INDEX `fk_turma7_idx` (`turma_id_turma` ASC),
  INDEX `fk_disciplina5_idx` (`id_disciplina` ASC),
  CONSTRAINT `fk_professor3`
    FOREIGN KEY (`id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma7`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disciplina5`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `escoladb`.`historico_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`historico_professor` (
  `id_historico` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `descricao` TEXT NOT NULL,
  `professor_id_professor` INT NOT NULL,
  PRIMARY KEY (`id_historico`),
  INDEX `fk_professor2_idx` (`professor_id_professor` ASC),
  CONSTRAINT `fk_professor2`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `escoladb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `ano_letivo` YEAR NOT NULL,
  `classe` VARCHAR(10) NOT NULL,
  `numero_matricula` VARCHAR(20) NOT NULL UNIQUE,
  `data_matricula` DATE NOT NULL,
  `turma_id_turma` INT NOT NULL,
  `aluno_id_aluno` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  `status_matricula` ENUM('ativa', 'trancada', 'cancelada') NOT NULL DEFAULT 'ativa',
  `comprovativo_pagamento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_turma6_idx` (`turma_id_turma` ASC),
  INDEX `fk_aluno3_idx` (`aluno_id_aluno` ASC),
  INDEX `fk_curso6_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_turma6`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aluno3`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `escoladb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_curso6`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `escoladb`.`curso` (`id_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`professor_tem_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor_tem_turma` (
  `professor_id_professor` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`professor_id_professor`, `turma_id_turma`),
  INDEX `idx_turma2` (`turma_id_turma` ASC),
  INDEX `idx_professor2` (`professor_id_professor` ASC),
  CONSTRAINT `fk_professor_tem_turma_professor`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_tem_turma_turma`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `escoladb`.`materiais_apoio_tem_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`materiais_apoio_tem_usuario` (
  `materiais_apoio_id_material` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`materiais_apoio_id_material`, `usuario_id_usuario`),
  INDEX `fk_materiais_apoio1_idx` (`materiais_apoio_id_material` ASC),
  INDEX `fk_usuario6_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_materiais_apoio1`
    FOREIGN KEY (`materiais_apoio_id_material`)
    REFERENCES `escoladb`.`materiais_apoio` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario6`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `escoladb`.`professor_tem_turma1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor_tem_turma1` (
  `professor_id_professor` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`professor_id_professor`, `turma_id_turma`),
  INDEX `idx_turma3` (`turma_id_turma` ASC),
  INDEX `idx_professor4` (`professor_id_professor` ASC),
  CONSTRAINT `fk_professor_tem_turma1_professor`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_tem_turma1_turma`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `escoladb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escoladb`.`documentos_administrativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`documentos_administrativos` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL,
  `caminho_arquivo` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `data_upload` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_usuario7_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_usuario7`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `escoladb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`planos_ensino`
-- -----------------------------------------------------
CREATE TABLE `escoladb`.`plano_ensino` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `ano_letivo` YEAR NOT NULL,
  `trimestre` ENUM('1', '2', '3') NOT NULL,
  `conteudo_programatico` TEXT NOT NULL,
  `metodologia` TEXT NOT NULL,
  `criterios_avaliacao` TEXT NOT NULL,
  `bibliografia` TEXT NOT NULL,
  `status` ENUM('rascunho', 'submetido', 'aprovado', 'rejeitado') NOT NULL DEFAULT 'rascunho',
  `data_submissao` DATETIME NULL,
  `data_aprovacao` DATETIME NULL,
  `id_disciplina` INT NOT NULL,
  `id_professor` INT NULL,
  `id_coordenador_aprovador` INT NULL,
  `caminho_arquivo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_plano`),
  INDEX `fk_disciplina_plano_idx` (`id_disciplina` ASC),
  INDEX `fk_professor_plano_idx` (`id_professor` ASC),
  INDEX `fk_coordenador_plano_idx` (`id_coordenador_aprovador` ASC),
  CONSTRAINT `fk_disciplina_plano`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `escoladb`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_professor_plano`
    FOREIGN KEY (`id_professor`)
    REFERENCES `escoladb`.`professor` (`id_professor`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_coordenador_plano`
    FOREIGN KEY (`id_coordenador_aprovador`)
    REFERENCES `escoladb`.`coordenador` (`id_coordenador`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
